require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'KwangWoonUniv_MileageService' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

    # Permissions (퍼미션 요청을 위한 코드 추가)
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
    
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'KwangWoonUniv_MileageServiceTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'KwangWoonUniv_MileageService-tvOS' do
  # Pods for KwangWoonUniv_MileageService-tvOS

  target 'KwangWoonUniv_MileageService-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
